export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const CLEAR_SINGLE_PROFILE = 'CLEAR_SINGLE_PROFILE';
export const GET_CARS = 'GET_CARS';
export const GET_CARS_USER_ID = 'GET_CARS_USER_ID';
export const GET_CAR = 'GET_CAR';
export const GET_PROFILE_BY_ID = 'GET_PROFILE_BY_ID';
export const GET_PROFILE_BY_USERNAME = 'GET_PROFILE_BY_USERNAME';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const DELETE_CAR = 'DELETE_CAR';
export const UPDATE_CAR = 'UPDATE_CAR';
export const CLEAR_CAR = 'CLEAR_CAR';
export const CLEAR_USER_CARS = 'CLEAR_USER_CARS';
export const FORM_LOADING = 'FORM_LOADING';
export const GET_PICTURES = 'GET_PICTURES';
export const CLEAR_PICTURES = 'CLEAR_PICTURES';
export const ADDING_PICTURES = 'ADDING_PICTURES';
export const UPDATE_PICTURES = 'UPDATE_PICTURES';
export const DELETE_PICTURES = 'DELETE_PICTURES';


